### ISSUE TITLE
Code Review - PindexTours

### ISSUE THREAD

**Issue by Dietech** [pindex/android#192]
This is a code review for the code of the whole project on master branch at commit https://github.com/pindex/android/tree/215d7a4d5f57ab9acb904cf33595923d3378d11e

Of course, we don't expect you to change all of your code (some parts of the review can be subjective or arguable anyway), what’s important is that you understand why better alternatives may exist.

**Please ask us if you have any question about the code review, whether it is by writing a comment below or by sending us a message on Discord/Email or meeting us.**

**Important : if you try to fix these, don't break your app. We prefer that the app works even if you don't manage to fix everything.**

# Packages

The overall package structure is very clean.

* The `data` package could be removed and the classes could be sorted in the other packages.
* The `services/favoriteRoom` package contains classes that don't have the suffix `Service`. Maybe `FavoriteDao.kt` could be moved to the `models` package and `FavoriteRoomDatabase.kt` could be renamed.
* The test class `favoriteRoomTest.kt` does not start with an uppercase letter.

# Class Naming

* Test classes should have the same name as the class under test with the `Test` suffix.

# Comments

Overall, the code is fairly well documented already, however some classes/interfaces are missing documentation. Remember that **all public classes, methods and fields must be documented.** This is especially important for interfaces where a lack of documentation makes them impossible to implement correctly.

# Code Style

We noticed inconsistencies in the way you name variables. Some of you do this:
```
private var string: String = "";
```
while some others do:
```
private var mString: String = "";
```
You should choose one and stick to it.

In anycase, you should program your codestyle (or use the default) in your IDE and use CTRL-ALT-L shortcut to reformat your files and optimise imports.

# Modularity

* Some services like `LoginService.kt` do not seem to provide any useful addition to their already existing repository counterpart.

# Abstractions

Very nice use of Hilt for dependency injection.

* The abstraction for the Glide library is missing which leaks a bit of Firebase specific semantics. This could be removed by making your `MediaLoader` an interface that fetches images from any URI. This removes the need to have a `fromFirebase` suffix to its methods, which breaks the rest of the abstraction.
* The `UserRepository.kt` returns `PindexUser` objects which have a reference to a Firebase object. Replacing the `FirebaseUser` from the `PindexUser` data object would solve this issue.

# Testing

Overall, there seems to be confusion on whether to put tests in `test` or `androidTest`. As a general rule, any class that requires an Android context (UI, Services, etc...) should be located in `androidTest`. Any other test class should be in `test`. E.g., fragments should be only tested in `androidTest` and repositories should only be tested in `test`.
Also make sure that every test actually tests something.

* Code/naming conventions are also applicable in test classes, i.e., method/class/variables names should follow the same pattern as the rest of your code.
* The block fragment tests in the unit test packages could be tested in the connected test package instead.
* `mediaSessionServiceIsCreated` in `MediaSessionTest.kt` does not test anything useful.
* Tests should validate only one feature/method. E.g., `RoomFavoriteWorks` in `favoriteRoomTest.kt` should be split in min. 4 different tests.
* The mock implementations of your repositories (`FirebaseMockExperienceRepository`, etc...) could be moved to the `androidTest` package as they are not used elsewhere.
* Some repository classes don't have test classes.

# Conclusion

Overall, your repository is well structured and you have made really good use of Hilt to manage your dependencies. This results in code that is really easy to maintain and test. Very nice!

However, testing is an area that still needs a bit of attention. Some classes are not tested at all and some tests don't assert anything. The testing section of this review should give you some information to start improving your test suite.

Good luck and keep up the good work!

**Comment by ToufiPF** [comment]
Just a quick comment on the way our viarables are named: By default, we don't put the prefix 'm' for our variables. 
The only moment we do so is when we have a private mutable LiveData, and that we expose it as a public non-mutable one. In that case, both variables have basically the same name except the private one has this prefix 'm', for mutable.
